name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Yandex Cloud login
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      -
        name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{secrets.YANDEX_REGISTRY_ID}}
          CR_REPO: ${{secrets.YANDEX_REPO_NAME}}
          IMAGE_TAG: ${{ github.sha }}
          VM_ID: ${{secrets.VM_ID}}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG
      -
        name: Deploy to Yandex Cloud VM
        env:
          CR_REGISTRY: ${{secrets.YANDEX_REGISTRY_ID}}
          CR_REPO: ${{secrets.YANDEX_REPO_NAME}}
          IMAGE_TAG: ${{ github.sha }}
          VM_ID: ${{secrets.VM_ID}}          
          YANDEX_OAUTH_TOKEN: ${{secrets.YANDEX_OAUTH_TOKEN}}
          MATTERMOST_BASE_URL: ${{secrets.MATTERMOST_BASE_URL}}
          MATTERMOST_TOKEN: ${{secrets.MATTERMOST_TOKEN}}
          YANDEX_TRACKER_BASE_URL: ${{secrets.YANDEX_TRACKER_BASE_URL}}
          YANDEX_CONNECT_BASE_URL: ${{secrets.YANDEX_CONNECT_BASE_URL}}
          YANDEX_ORG_ID: ${{secrets.YANDEX_ORG_ID}}
          YANDEX_TOKEN: ${{secrets.YANDEX_TOKEN}}
          SERVICE_ADDRESS: ${{secrets.SERVICE_ADDRESS}}
          JIRA_SERVER_PERSONAL_TOKEN: ${{secrets.JIRA_SERVER_PERSONAL_TOKEN}}
          JIRA_SERVER_BASE_URL: ${{secrets.JIRA_SERVER_BASE_URL}}
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a
          eval "$(cat ~/.bashrc | tail -n +10)"
          source ~/.bashrc
          yc config set token $YANDEX_OAUTH_TOKEN
          yc compute instance update-container $VM_ID --container-env JIRA_SERVER_PERSONAL_TOKEN=$JIRA_SERVER_PERSONAL_TOKEN --container-env JIRA_SERVER_BASE_URL=$JIRA_SERVER_BASE_URL --container-env SERVICE_ADDRESS=$SERVICE_ADDRESS  --container-env MATTERMOST_BASE_URL=$MATTERMOST_BASE_URL --container-env MATTERMOST_TOKEN=$MATTERMOST_TOKEN --container-env YANDEX_CONNECT_BASE_URL=$YANDEX_CONNECT_BASE_URL --container-env YANDEX_ORG_ID=$YANDEX_ORG_ID --container-env YANDEX_TOKEN=$YANDEX_TOKEN  --container-env YANDEX_TRACKER_BASE_URL=$YANDEX_TRACKER_BASE_URL --container-image cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG

